package edu.usu;

import java.awt.Graphics2D;

public interface GameControl {
	
	//UPDATE WILL BE CALLED EVERY FRAME. YOU WILL ALL CALL THE 
	//ON COLLISION FUNCTION FROM THE UPDATE FUNTION IF THERE IS A COLLISION
	void Update();
	
	//ONCOLLISION IS CALLED ONLY IF THE GAMEOBJECT IS COLLIDING WITH OTHER OBJECTS
	//EVERY FRAME WILL CHECK ALL COLLISIONS AND THEN PASS THE COLLIDING OBJECTS INTO THE 
	//ONCOLLISION FUNCTION
	void OnCollision(GameObject other);
	
	//BASICALLY TREAT THIS AS THE CONSTRUCTOR. THE REASON THAT WE HAVE ANOTHER FUNCTION
	//DOES EXACTLY THE SAME THING AS THE CONSTRUCTOR IS SO THAT WE CAN REUSE GAME OBJECTS
	//WITHOUT HAVING TO INSTANTIATE THEM AGAIN BECAUSE ITS VERY COSTLY
	void OnEnable();
	
	//THIS FUNCTION WILL CALL WHEN WE REMOVE AN OBJECT FROM THE GAME. WE ARE USING THIS AS
	//A DESTRUCTOR SO THAT WE CAN REMOVE OBJECTS FROM GAME WITHOUT REMOVING THEM FROM MEMORY
	//SO THEY CAN BE REUSED.
	void OnDisable();
	
	//THIS FUNCTION IS CALLED AT THE BEGINNING OF THE GAME AND CALLED EVERY FRAME IF THE
	//VISUAL REPRESENTATION OF YOUR GAME OBJECT HAS CHANGED DURING THE UPDATE.
	//REALISTICALLY THIS FUNCTION SHOULD JUST SAY g.drawImage(posX, posY, ... );
	//THIS WILL DRAW THE VISREP IMAAGE TO THE SCREEN
	void PaintToScreen(Graphics2D g);
}
